-- Seed dataset for Search Typeahead System
-- ON CONFLICT ensures that restart of container doesn't cause primary key issues

INSERT INTO query_entry (query_text, total_count, recent_count, last_searched_at) VALUES
-- General Tech & Programming Languages
('java', 1500, 300, CURRENT_TIMESTAMP),
('javascript', 1200, 400, CURRENT_TIMESTAMP),
('python', 1100, 250, CURRENT_TIMESTAMP),
('c++', 800, 150, CURRENT_TIMESTAMP),
('c#', 750, 120, CURRENT_TIMESTAMP),
('golang', 950, 280, CURRENT_TIMESTAMP),
('rust', 700, 190, CURRENT_TIMESTAMP),
('typescript', 850, 220, CURRENT_TIMESTAMP),
('kotlin', 500, 90, CURRENT_TIMESTAMP),
('swift', 480, 85, CURRENT_TIMESTAMP),
('ruby on rails', 300, 45, CURRENT_TIMESTAMP),
('php programming', 400, 50, CURRENT_TIMESTAMP),
('sql query tutorial', 900, 210, CURRENT_TIMESTAMP),
('html5 template', 650, 130, CURRENT_TIMESTAMP),
('css3 flexbox', 600, 110, CURRENT_TIMESTAMP),
('bash scripting guide', 350, 75, CURRENT_TIMESTAMP),

-- Java Specific Queries (for rich typing autocomplete tests)
('java tutorial for beginners', 1400, 220, CURRENT_TIMESTAMP),
('java 17 features', 1300, 250, CURRENT_TIMESTAMP),
('java virtual machine architecture', 980, 140, CURRENT_TIMESTAMP),
('java stream api tutorial', 920, 190, CURRENT_TIMESTAMP),
('java spring boot integration', 880, 280, CURRENT_TIMESTAMP),
('java arraylist vs linkedlist', 820, 120, CURRENT_TIMESTAMP),
('java design patterns pdf', 780, 150, CURRENT_TIMESTAMP),
('java concurrency interview questions', 750, 100, CURRENT_TIMESTAMP),
('java memory leak analysis', 450, 60, CURRENT_TIMESTAMP),
('java garbage collection tuning', 520, 75, CURRENT_TIMESTAMP),
('java lambda expressions', 670, 115, CURRENT_TIMESTAMP),
('java reflection api', 380, 40, CURRENT_TIMESTAMP),
('java multithreading examples', 710, 95, CURRENT_TIMESTAMP),
('java compiler online', 1150, 180, CURRENT_TIMESTAMP),

-- Spring Boot Specific Queries
('spring boot tutorial', 1800, 200, CURRENT_TIMESTAMP),
('spring boot security configure', 950, 180, CURRENT_TIMESTAMP),
('spring boot jpa repository', 1100, 210, CURRENT_TIMESTAMP),
('spring boot microservices', 1250, 310, CURRENT_TIMESTAMP),
('spring boot dockerfile example', 890, 150, CURRENT_TIMESTAMP),
('spring boot actuary metrics', 420, 65, CURRENT_TIMESTAMP),
('spring boot dependency injection', 720, 95, CURRENT_TIMESTAMP),
('spring boot rest api responseentity', 830, 140, CURRENT_TIMESTAMP),

-- Databases & Caching
('postgresql database install', 700, 50, CURRENT_TIMESTAMP),
('postgresql optimization index', 580, 95, CURRENT_TIMESTAMP),
('mysql vs postgresql benchmark', 810, 120, CURRENT_TIMESTAMP),
('redis cache aside pattern', 800, 150, CURRENT_TIMESTAMP),
('redis distributed lock', 620, 110, CURRENT_TIMESTAMP),
('redis pub sub spring boot', 490, 85, CURRENT_TIMESTAMP),
('redis cluster setup tutorial', 550, 90, CURRENT_TIMESTAMP),
('mongodb aggregation pipeline', 680, 105, CURRENT_TIMESTAMP),
('sqlite database browser', 410, 55, CURRENT_TIMESTAMP),
('database normalization 1nf 2nf 3nf', 920, 160, CURRENT_TIMESTAMP),

-- DevOps & Infrastructure
('docker compose up build', 900, 100, CURRENT_TIMESTAMP),
('docker command cheat sheet', 1050, 195, CURRENT_TIMESTAMP),
('kubernetes architecture explained', 850, 140, CURRENT_TIMESTAMP),
('kubernetes pod lifecycle', 600, 90, CURRENT_TIMESTAMP),
('jenkins pipeline tutorial', 730, 80, CURRENT_TIMESTAMP),
('ansible playbook examples', 480, 65, CURRENT_TIMESTAMP),
('terraform aws infrastructure', 690, 110, CURRENT_TIMESTAMP),
('git checkout branch remote', 1120, 250, CURRENT_TIMESTAMP),
('git merge vs rebase difference', 980, 185, CURRENT_TIMESTAMP),
('github actions workflow yaml', 870, 170, CURRENT_TIMESTAMP),

-- System Design & Distributed Systems (extremely Viva friendly)
('consistent hashing ring simulation', 950, 450, CURRENT_TIMESTAMP),
('system design interview guide', 1200, 320, CURRENT_TIMESTAMP),
('load balancing algorithms round robin', 790, 130, CURRENT_TIMESTAMP),
('reverse proxy vs forward proxy', 910, 175, CURRENT_TIMESTAMP),
('api gateway microservices pattern', 830, 145, CURRENT_TIMESTAMP),
('database sharding vs partitioning', 760, 110, CURRENT_TIMESTAMP),
('caching strategies write through', 690, 95, CURRENT_TIMESTAMP),
('cdn content delivery network wiki', 590, 70, CURRENT_TIMESTAMP),
('rate limiting algorithms token bucket', 720, 115, CURRENT_TIMESTAMP),
('microservices design principles', 810, 125, CURRENT_TIMESTAMP),
('monolith to microservices migration', 540, 80, CURRENT_TIMESTAMP),
('message queue kafka vs rabbitmq', 890, 160, CURRENT_TIMESTAMP),
('event driven architecture patterns', 620, 95, CURRENT_TIMESTAMP),

-- Web Development & Frontend Frameworks
('react tutorial for beginners', 2000, 500, CURRENT_TIMESTAMP),
('react hooks tutorial useeffect', 1150, 280, CURRENT_TIMESTAMP),
('react state management context api', 920, 190, CURRENT_TIMESTAMP),
('react virtual dom explanation', 780, 110, CURRENT_TIMESTAMP),
('angular vs react vs vue', 850, 140, CURRENT_TIMESTAMP),
('vue js dynamic components', 510, 75, CURRENT_TIMESTAMP),
('next js server side rendering', 970, 240, CURRENT_TIMESTAMP),
('tailwind css responsive layout', 890, 195, CURRENT_TIMESTAMP),
('vite build configuration react', 680, 130, CURRENT_TIMESTAMP),
('nodejs express rest api', 1000, 350, CURRENT_TIMESTAMP),

-- Popular General Internet Queries
('chatgpt plus vs free tier', 2500, 600, CURRENT_TIMESTAMP),
('openai api documentation', 1400, 350, CURRENT_TIMESTAMP),
('google maps platform', 1100, 150, CURRENT_TIMESTAMP),
('stack overflow developer survey', 900, 120, CURRENT_TIMESTAMP),
('artificial intelligence trends', 1600, 450, CURRENT_TIMESTAMP),
('machine learning algorithms python', 1300, 310, CURRENT_TIMESTAMP),
('deep learning vs neural networks', 950, 210, CURRENT_TIMESTAMP),
('weather today hourly forecast', 3000, 1000, CURRENT_TIMESTAMP),
('latest technology news updates', 1800, 550, CURRENT_TIMESTAMP),

-- Generic Searches (iPhone, Shopping, Life, Cooking)
('iphone 15 pro max review', 2800, 900, CURRENT_TIMESTAMP),
('iphone vs samsung camera comparison', 2100, 450, CURRENT_TIMESTAMP),
('iphone 16 release date leaks', 2600, 850, CURRENT_TIMESTAMP),
('iphone battery health tips', 1700, 320, CURRENT_TIMESTAMP),
('iphone screen repair service cost', 1200, 180, CURRENT_TIMESTAMP),
('iphone backup to icloud guide', 1450, 250, CURRENT_TIMESTAMP),
('best movies on netflix right now', 2400, 750, CURRENT_TIMESTAMP),
('how to cook pasta perfectly', 1900, 400, CURRENT_TIMESTAMP),
('chocolate chip cookies easy recipe', 1650, 350, CURRENT_TIMESTAMP),
('how to make coffee at home without machine', 1500, 280, CURRENT_TIMESTAMP),
('cheap flights to new york city', 2200, 600, CURRENT_TIMESTAMP),
('google flights search engine', 2700, 800, CURRENT_TIMESTAMP),
('how to lose weight fast healthily', 2000, 550, CURRENT_TIMESTAMP),
('how to sleep better at night', 1850, 420, CURRENT_TIMESTAMP),
('what is my ip address lookup', 3200, 1100, CURRENT_TIMESTAMP),
('best wireless earbuds under 100', 1600, 380, CURRENT_TIMESTAMP),
('smart watch budget options 2024', 1350, 290, CURRENT_TIMESTAMP),
('tesla model y price drop', 1950, 490, CURRENT_TIMESTAMP),
('spotify web player online', 2900, 950, CURRENT_TIMESTAMP),
('instagram login account mobile', 3100, 1050, CURRENT_TIMESTAMP),
('facebook password reset security', 2450, 500, CURRENT_TIMESTAMP),
('amazon prime video streaming', 2800, 850, CURRENT_TIMESTAMP)
ON CONFLICT (query_text) DO NOTHING;
